[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tech_challenge_fase_1"
version = "0.0.1"
description = "Projeto Final Fase 1 MLET10"
authors = [
  { name = "MLEKs" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "fastapi>=0.136.1",
  "joblib",
    "numpy",
    "pandas",
    "pydantic-settings>=2.0.0",
    "python-dotenv",
    "requests>=2.32.0",
    "ruff",
    "scikit-learn",
    "seaborn>=0.13.2",
    "streamlit>=1.45.0",
    "tabulate>=0.10.0",
    "uvicorn>=0.46.0",
    "imbalanced-learn>=0.11.0",
    "torch>=2.12.0",
]
requires-python = "~=3.12.0"

[project.optional-dependencies]
train = [
  "fairlearn>=0.13.0",
  "huggingface-hub>=1.16.1",
  "mlflow>=3.12.0",
  "openpyxl>=3.1.5",
]
docs = [
  "great-tables[img]>=0.9.0",
  "jinja2>=3.1.6",
  "mkdocs",
]
notebook = [
  "ipython",
  "jupyterlab",
  "matplotlib",
  "notebook",
  "seaborn>=0.13.2",
  "tabulate>=0.10.0",
]
dev = [
  "pandera>=0.21.0",
  "pip",
  "pytest",
  "pytest-sugar",
  "ruff",
]


[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ml_pipeline", "utils"]
force-sort-within-sections = true

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "--ignore=src/ml_pipeline -q"

[tool.flit.module]
name = "ml_pipeline"
