apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api
  labels:
    app: tech-challenge-api
spec:
  type: ClusterIP
  selector:
    app: tech-challenge-api
  ports:
    - name: http
      port: 80
      targetPort: http